name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install dependencies
      run: just install

    - name: Build gopy library
      run: just build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gopy-library
        path: src/
