name: Build and Publish

on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64, macos-latest, windows-latest] # Define the OS matrix
        python-version: [3.12, 3.13] # Optional: Add Python versions if needed

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install dependencies
      run: just install

    - name: Build gopy library
      run: just build
      
    - name: Make library into distributable
      run: just dist

    - name: Upload artifacts
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: trino_concurrency_executor__gopy-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/

    - name: Upload arifact to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} ./dist/*.whl